{
 "title": "sfvis01",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT Workstation_Camera FROM test.sfvis_cam1;\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 10, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT Vision_System FROM test.sfvis01;\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT Workstation_Camera FROM test.sfvis_cam2;\n"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT New_Status, Old_Status, Timestamp FROM test.sfvis_cam1 ORDER BY Timestamp DESC LIMIT 4;\n"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 7 },
   "content": "<div style=\\\"text-align: center;\\\">\n<img src=\"http://sfgrafana.sf.local/Full_Transparent_Background.png\" alt=\"Grafana Image\" style=\"width:100%; height:auto; top:100%\">  \n\n\n\n"
  },
  {
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT New_Status, Old_Status, Timestamp FROM test.sfvis_cam2 ORDER BY Timestamp DESC LIMIT 4;\n"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT People_Count FROM test.sfvis_cam1;",
     "title": "Camera"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT People_Count FROM test.sfvis_cam2;",
     "title": "Camera"
    }
   ]
  },
  {
   "title": "Presence per Minute",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT Presence_Change_Rate FROM test.sfvis_cam1;\n"
    }
   ]
  },
  {
   "title": "Total Presence - Cam 1",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT Presence_Change_Total FROM test.sfvis_cam1;\n"
    }
   ]
  },
  {
   "title": "Total Presence - Cam 2",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT Presence_Change_Total FROM test.sfvis_cam1;\n"
    }
   ]
  },
  {
   "title": "Presence per Minute",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT Presence_Change_Rate FROM test.sfvis_cam1;\n"
    }
   ]
  },
  {
   "title": "Frame Rate",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT Frame_Rate FROM test.sfvis_cam1;\n"
    }
   ]
  }
 ]
}